### ISSUE TITLE
Make gh-pages default branch

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro#17]
This has been done in the other LC repos.

**Comment by drjwbaker** [comment]
Sure. No idea how this is done though..

**Comment by ccronje** [comment]
It's done via Settings > Branches but I think you must have 'write' permissions if you can't see Settings but can merge PRs - @weaverbel will probably have admin.

This explains the diffs https://help.github.com/articles/repository-permission-levels-for-an-organization/

**Comment by drjwbaker** [comment]
@ccronje Done it. Can you request to join https://github.com/orgs/data-lessons/teams/library? If you can you should!

**Comment by ccronje** [comment]
Thanks @drjwbaker, I can't see the link or a way to request. It looks like membership/teams managed via org settings.
