### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-data-intro#19]
Contact details here http://data-lessons.github.io/library-data-intro/ go to macdonellc4@macewan.ca and on http://data-lessons.github.io/library-openrefine/ to gvwilson@software-carpentry.org

We need to relieve Greg of more email and standardise this across the repos. @cmacdonell, given that your name is on one, was the a deliberate change and are you happy to take the email? Perhaps the lesson maintainer can take the traffic?

**Comment by weaverbel** [comment]
@drjwbaker Is this still an issue?

**Comment by drjwbaker** [comment]
@weaverbel Nope. I've resolved this! (thanks for going round tidying up!)
