### ISSUE TITLE
Create library-overview repo & site with links to all lessons

### ISSUE THREAD

**Issue by jcoliver** [data-lessons/library-data-intro#21]
These are great resources! I would love to be able to send my library colleagues to a single (non-README) site with all the lessons listed. If such a resource exists already, where is it? If it doesn't exist, could a very small repo be established with links to each of the lessons? The links in the README work fine for those comfortable with GitHub, but a novice-friendly overview page, presented like the index.html pages for each lesson would be easier for many folks to navigate (If someone on the data-lessons project wants to create the repo, I can take a first pass at the index.html).

**Comment by drjwbaker** [comment]
Dear Jeff / @jcoliver  - welcome to the Library Carpentry community! This is really useful feedback and I totally agree with you, thank you. There is a slightly dormant repo https://github.com/LibraryCarpentry/librarycarpentry.github.io which points to the simple but effective http://librarycarpentry.github.io/. This could be a good repo to make a first pass at? I've added you as a collaborator if you are willing and able to make the first pass!

**Comment by ccronje** [comment]
Thanks for doing this @jcoliver, nice solution!
