### ISSUE TITLE
Giving Greg contributor access

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-data-intro#23]
@ccronje Remind me, who has the power to add @gvwilson as a contributor to this repo? (so he can assign himself pull requests et cetera) @tracykteal as owner? Greg needs the ability to do this across all our modules.

**Comment by drjwbaker** [comment]
Sorted by @weaverbel

**Comment by ccronje** [comment]
@drjwbaker Tracy has added people to date but not sure who has the same permissions - ping @weaverbel.
