### ISSUE TITLE
Missing slides

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro#24]
@drjwbaker It looks like we're missing your slide deck since the template updates.

**Comment by drjwbaker** [comment]
@ccronje Good catch. Seen as you are doing this next, is there a better way of making the information available for trainers than a slide deck? Perhaps rather than the **SLIDE** note we can put

> information that might go in a slide as a quote callout like this?

Happy to implement that if you agree.

**Comment by ccronje** [comment]
@drjwbaker I wonder if a [Challenge/Solution](http://swcarpentry.github.io/lesson-example/04-formatting/) approach could work for the slide content @weaverbel discusses in #25? ([this Shell episode has an example](http://data-lessons.github.io/library-shell/02-counting-mining/)). The 'callout' boxes look like a great way of capturing the other slide content.

**Comment by weaverbel** [comment]
+1 to having slide material in a quote callout. @drjwbaker @ccronje

**Comment by drjwbaker** [comment]
Per https://github.com/data-lessons/library-data-intro/issues/25, I shall build in challenge/solution/explanation using the model at http://data-lessons.github.io/library-shell/02-counting-mining/ With luck I will get to this this week, marking willing!

**Comment by drjwbaker** [comment]
So, I made a start http://data-lessons.github.io/library-data-intro/04-regular-expressions/ (nb, I've worked through the previous one's removing **SLIDE** markers and adding info where required). Hope this is what you had in mind. I shall finish tomorrow!

**Comment by ccronje** [comment]
Excellent @drjwbaker - thank you!

**Comment by weaverbel** [comment]
Super super super fantastic ! Love your work @drjwbaker !

**Comment by drjwbaker** [comment]
Ta very much. Done now.
