### ISSUE TITLE
Sprint tasks for the data intro lesson

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-data-intro#29]
@ccronje Pinging for a quick chat on general tasks for this lesson during the sprint.

I think I will revise http://data-lessons.github.io/library-data-intro/02-jargon-busting/ based on what I did in Pittsburgh. @ndalyrose and I will work on more regex https://github.com/data-lessons/library-data-intro/issues/27. Anything else?

**Comment by ccronje** [comment]
@drjwbaker fresh eyes are always welcome, so reading over the lesson and offering suggestions (e.g. typos or descriptions) could be a task? For people who have delivered the lesson, perhaps a task could be sharing tips/feedback/lessons learned?

**Comment by drjwbaker** [comment]
Both good ideas, especially an issue on getting feedback from those who've taught it.

**Comment by pitviper6** [comment]
Maybe the tips/lessons learned can be part of the instructor sheet we are thinking of doing for the lessons?

**Comment by drjwbaker** [comment]
I've done lots of work on all of the lesson apart from the regex bits: revised learning outcomes, rationalised tasks, developed instructor notes, added a handout.

So I'm closing this for now!
