### ISSUE TITLE
QA Regex quiz

### ISSUE THREAD

**Issue by drjwbaker** [data-lessons/library-data-intro#5]
It would be great if someone with regex knowledge could Q&A the new regex quiz at https://github.com/data-lessons/library-data-intro/blob/master/lesson-materials/LibCarp-introtodata-handout.md#multiple-choice-quiz (answers at https://github.com/data-lessons/library-data-intro/blob/master/lesson-materials/LibCarp-introtodata-answers.md) and if someone else whose less regex confident could take the quiz, report back on their score, and rate the quiz in terms of difficulty. It could well benefit from additions, more questions at different levels, et cetera.

If you pick this up, make yourself known and someone can assign the issue to you.

**Comment by pitviper6** [comment]
I'll take the quiz and report back - I'm a novice at regex!

Juliane.

**Comment by pitviper6** [comment]
I did quite a bit of Regex about 10 years ago and of course have since forgotten it, but I thought it was just the right amount of difficult for this level.  I got a score of 9 on the quiz.

Two out of the three I got wrong (q. 8-10) involved my forgetting that there isn't a space when you use the "or" operator |.  So I in essence I think questions 8 and 9 are testing the same thing. Otherwise, I think it covers basic regex concepts really well!

**Comment by ccronje** [comment]
I fall into the newbie category. The difficulty is good. I was shaky on 10 and tripped up on 12. It would be fun to have a few more curly ones like 12, maybe text-based (perhaps the data Owen sent for the OpenRefine/SQL repos!) - thanks @drjwbaker this is such a great idea! :-)

**Comment by clintonroy** [comment]
I think question 6 is wrong, the regexes all have capital leading R characters, but the strings they're meant to match with don't.

**Comment by clintonroy** [comment]
Question one, I'm not perfectly happy with the word 'specific' in the question, as * doesn't match any particular character at all, it just modifies what the previous match is. This a minor quibble though.

**Comment by weaverbel** [comment]
@clintonroy @drjwbaker I changed the R to lower case in question 6.

**Comment by drjwbaker** [comment]
Thanks all! I've removed specific from Q1 (quite right @clintonroy). Agreed there is perhaps the need for 2/3 more than bridge the last problem. The last one is one there as that is a regex I wrote recently to solve a problem, so I guess if anyone has some real world regex to add to the quiz, that would be great.
