### ISSUE TITLE
Add link to Library Carpentry on lesson pages

### ISSUE THREAD

**Issue by jcoliver** [data-lessons/library-data-intro#51]
In looking over the data intro lesson, I could not find a link to the home page of Library Carpentry (http://librarycarpentry.github.io/). Perhaps at the bottom of lesson pages, where copyright information is found, the link could be to librarycarpentry.github.io (most lessons appear to have self-referential links [i.e. <a href="">Library Carpentry</a> links to whatever the current page is]).

**Comment by drjwbaker** [comment]
@jcoliver Good catch. Looks like this is a LC wide issue. SWC - eg http://swcarpentry.github.io/shell-novice/ - has a link to the SWc website in the footer (click the link next to the copyright sign). Given ongoing development to the LC webpage https://github.com/LibraryCarpentry/librarycarpentry.github.io/issues/32 should probably deal with this across lessons.

Are you interested in / able to raise PRs across the LC lessons to fix this?

**Comment by jcoliver** [comment]
@drjwbaker Sure, I can try to fix it via PRs. But probably not today :)

**Comment by drjwbaker** [comment]
@jcoliver Thanks Jeff. That is a huge help!
