### ISSUE TITLE
Exercises in Foundations Episode

### ISSUE THREAD

**Issue by kekoziar** [data-lessons/library-data-intro#55]
The episode Foundations indicates 15 minutes for exercises, but no exercises are included.  Is there a suggested exercise? What have those who have taught this lesson used?

**Comment by weaverbel** [comment]
Hi @kekoziar I do this as a show and tell - no exercise that they do. I also usually show them a bit of markdown and how using pandoc, you can turn that simple markup into a PDF, HTML page or formatted Word doc - all from the one file source. 

Generally get a bit of ooohing and ahhing at that ! 

For the markdown file examples, I do bold, italic, bulleted list, numbered list, web link and an image and then show them how all that renders in the different output files.
