### ISSUE TITLE
Proposed learning objective

### ISSUE THREAD

**Issue by michielcock** [data-lessons/library-data-intro#6]
After completing this lessons, you can:

* explain terms, phrases, or ideas around code or software development that you've come across and perhaps feel you should know better
* explain and use some best practices and generic skills in using computation
* do searches using regular expressions

**Comment by weaverbel** [comment]
Slightly rewording these @michielcock - what do you think?

After completing this lesson, you should be able to:

understand terms, phrases, and concepts in software development and data science
identify and use best practice in data structures
use regular expressions in searches

**Comment by drjwbaker** [comment]
Good. Can someone gh-pages template this repo (sorry, no idea how to do that) so I can start adding in these objectives. Ta!

**Comment by weaverbel** [comment]
Hi @drjwbaker `gh-pages` already done for this repo. From this page:
https://github.com/data-lessons/library-data-intro
switch from `Branch: master` (it's a drop down option just above the list of files) to `Branch: gh-pages` and voila - the whole structure be there !

**Comment by drjwbaker** [comment]
Ah. Missed that. Was being thick. Great job.

**Comment by ccronje** [comment]
The learning objectives have been included in #14 #15 #16 - @weaverbel can you please have a look over these and #13 when you get a chance? Wondering if there's more to add post https://twitter.com/hashtag/lc_bris?f=tweets&vertical=default&src=hash workshop.
