### ISSUE TITLE
Maintaining the lesson

### ISSUE THREAD

**Issue by weaverbel** [data-lessons/library-data-intro#7]
@ccronje has volunteered as a maintainer

**Comment by drjwbaker** [comment]
@ccronje Happy to back up on that. See my comment on https://github.com/data-lessons/library-data-intro/issues/6 about gh-pagesing this.

**Comment by weaverbel** [comment]
@drjwbaker @ccronje This lesson already has gh-pages set up. see my response https://github.com/data-lessons/library-data-intro/issues/6

**Comment by weaverbel** [comment]
Closing this now we have two maintainers.
Belinda
