### ISSUE TITLE
proposed _episodes

### ISSUE THREAD

**Issue by ccronje** [data-lessons/library-data-intro#8]
Split LibCarp-introdata.md into:
> 01-introduction.md (~15min)
> 02-jargon-busting.md (45min)
> 03-foundations.md (45min)
> 04-regular-expressions.md (45min)

Rename LibCarp-introdata-handout.md to:
> 05-handout-questions.md

Rename LibCarp-introdata.answers.md to:
> 06-handout-answers.md

Or should we combine 05 & 06? (it could be considered a 45min episode)

The slide deck files (LibCarp-introdata-deck.pdf/odp) are not episodes so where should they be placed in the new structure? Or would it be better to create an "Instructors' Guide" based on this content? Note: LibCarp-introdata.md references the slide deck with "SLIDE" throughout but this is easy enough to change.

@weaverbel let me know and I'll go ahead with the changes

**Comment by weaverbel** [comment]
@ccronje - my thoughts (and thanks for all the hard yakka)

+1 to the split
+1 to renaming handout
+1 to renaming answers
-1 to combining 05 and 06 for now
Can we turn the slides into markdown - then they can be output in heaps of different ways via pandoc?

**Comment by ccronje** [comment]
@weaverbel Yes @ptsefton helped me convert the slides (odp file) to markdown - I'll put this in the Instructors' Guide. Aiming to have these things done by tomorrow.

**Comment by drjwbaker** [comment]
agreed with @weaverbel on the split/not split (answers and handout need to be a separate sheet so it is clear that a) they are printed separately and b) they are handed out separately)

On slides, the **SLIDE** bits as a Jamesism carried over into public content. If @ccronje can get them into .md that can be pandoced that would be great (and I would learn something, I use pandoc a lot but never for slides)

**Comment by ccronje** [comment]
The initial pass of the above is done. The first PR includes six updated/new _episode files. The header content needs checking across all. I'm sure there is a lot left to tweak - just let me know what to address next. Am new to the DC templates but it is well documented :-)

Please double check the slide deck (_extras/guide.md) as the conversion from odp to md inserted a lot of escapes (disturbing the regex gah!). I'd like to see how pandoc works with this file too. In ref to #9 the license is now CC BY on the first slide.

**Comment by drjwbaker** [comment]
@ccronje  On the second PR, I couldn't get your guide.md to pandoc to a html slide deck so I made another one that I could easily - with a little reading around - using slidy. If so sync up and open the file it should work fine (needs a little fettling, but it was my first stab!)

**Comment by ccronje** [comment]
@drjwbaker great job, works a treat - please overwrite guide.md
@weaverbel I have Jekyll on my local now so can preview properly - I can see what needs fixing in the episodes so will get onto that this evening.

**Comment by drjwbaker** [comment]
@ccronje Okay. On your guide.md did that render as a deck for a purpose? No need to get rid of it if it will work as an alternative deck for an alternative setup.

**Comment by ccronje** [comment]
@drjwbaker it was a first attempt so not fully tested. Fine to remove until I get more experience under belt.

**Comment by drjwbaker** [comment]
Okay.
